### PR TITLE
Update to the latest version

### PR DESCRIPTION
**Pull request by susannasiebert**

### CODE REVIEW

**Review by tmooney — APPROVED** [review]
+1, I see https://pypi.org/project/pvactools/1.1.3/ exists!

**Comment by tmooney** [comment]
As a side note, we should maybe give some thought into a process for doing this that doesn't temporarily lead to the creation of a new docker tag but pointing to the old version of the Dockerfile.  This comes up a lot with our Docker repos.

**Comment by susannasiebert** [comment]
@tmooney an alternative might be to make the PR to master and then make a branch off of master once the PR is merged.

**Comment by tmooney** [comment]
That seems like a good strategy--then `latest` gets updated with the new release "for free", too!

**Pull request merged**
